language: node_js
node_js:
  - "20"

services:
  - docker

cache:
  directories:
    - node_modules

script:
  - npm install
  - npm run build
  - npm test -- --watchAll=false
  - docker build -t my-react-app .
