name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Install EB CLI
        run: |
          pip install --upgrade --user awsebcli
          export PATH=$PATH:~/.local/bin
          eb --version

      - name: Deploy to Elastic Beanstalk
        run: |
          export PATH=$PATH:~/.local/bin
          zip -r deploy.zip . -x "*.git*" "node_modules/*"
          eb init MyReactApp --platform "Node.js 20" --region eu-north-1
          eb use MyReactApp-env
          eb deploy
